[package]
name = "dart-api-dl-sys"
version = "0.4.0+2.0.0"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.64.0"

[dev-dependencies]
static_assertions = "1.1.0"

[build-dependencies]
bindgen = "0.60.1"
cc = "1.0.73"
