[workspace]
members = [
    "dart-api-dl",
    "dart-api-dl-sys",
    "integration-tests-bindings",
    "update-lib",
]
resolver = "2"

[patch.crates-io]
xayn-dart-api-dl-sys = { path = "./dart-api-dl-sys" }
xayn-dart-api-dl = { path = "./dart-api-dl" }
